
name: Update Commit Activity Chart

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:    # Allows you to run it manually

jobs:
  update-chart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Generate updated chart
        run: |
          python generate_chart.py

      - name: Commit and push updated chart
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add commit_activity_chart.png
          git commit -m "Update commit activity chart [skip ci]" || echo "No changes to commit"
          git push
